### ISSUE TITLE
Issue with python 3.4.2

### ISSUE THREAD

**Issue by grandtiger** [filmackay/blpapi-py#1]
Hi there, I tried the branch for python 3, but got some error. I am new to python and don't know how to fix it. Could you please take a look when you get a chance? Thanks a lot in advance!

```
import blpapi
options = blpapi.SessionOptions()
options.setServerHost('localhost')
options.setServerPort(8194)
session = blpapi.Session(options)
session.start()
session.openService("//blp/refdata")
refDataService = session.getService("//blp/refdata")
request = refDataService.createRequest("HistoricalDataRequest")

### work up to this point, the next line give the following error
###>>> request.getElement("securities").appendValue("IBM US Equity")
###Traceback (most recent call last):
###  File "<stdin>", line 1, in <module>
###  File "C:\Python34\lib\site-packages\blpapi\element.py", line 675, in appendValue
###    self.setValue(value, internals.ELEMENT_INDEX_END)
###  File "C:\Python34\lib\site-packages\blpapi\element.py", line 650, in setValue
###    _ExceptionUtil.raiseOnError(traits[1](self.__handle, value, index))
###OverflowError: in method 'blpapi_Element_setValueString', argument 3 of type 'size_t'

request.getElement("securities").appendValue("IBM US Equity")
request.getElement("securities").appendValue("MSFT US Equity")
request.getElement("fields").appendValue("PX_LAST")
request.getElement("fields").appendValue("OPEN")
request.set("periodicityAdjustment", "ACTUAL")
request.set("periodicitySelection", "MONTHLY")
request.set("startDate", "20060101")
request.set("endDate", "20061231")
request.set("maxDataPoints", 100)
print("Sending Request:", request)
session.sendRequest(request)
```

**Comment by 691175002** [comment]
I am getting this error on Windows 7 x32.

Is this expected with 32 bit windows or am I doing something wrong?

**Comment by filmackay** [comment]
Not expected with 32-bit, no. It "should" work - never tried. Is it easy for you to try 64-bit to eliminate whether this is the relevant factor?

**Comment by 691175002** [comment]
I think I got it, looks like this when installing:

    Setting SDK environment relative to C:\Program Files\Microsoft SDKs\Windows\v7.1
    \.
    Targeting Windows 7 x86 Release

    H:\blpapi-py-master>activate pyq
    Activating environment "pyq"...

    [pyq] H:\blpapi-py-master>python setup.py build --compiler msvc
    running build
    running build_py
    running build_ext
    building 'blpapi._internals' extension
    c:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /
    W3 /GS- /DNDEBUG -IC:\blp\API\APIv3\C++API\v3.7.5.1\include -IC:\Anaconda\envs\p
    yq\include -IC:\Anaconda\envs\pyq\include /Tpblpapi/internals_wrap.cxx /Fobuild\
    temp.win32-3.4\Release\blpapi/internals_wrap.obj
    internals_wrap.cxx
    c:\Program Files\Microsoft Visual Studio 10.0\VC\INCLUDE\xlocale(323) : warning
    C4530: C++ exception handler used, but unwind semantics are not enabled. Specify
     /EHsc
    blpapi/internals_wrap.cxx(3921) : warning C4244: 'argument' : conversion from 'b
    lpapi_Float64_t' to 'blpapi_Float32_t', possible loss of data
    blpapi/internals_wrap.cxx(3935) : warning C4244: 'argument' : conversion from 'b
    lpapi_Float64_t' to 'blpapi_Float32_t', possible loss of data
    blpapi/internals_wrap.cxx(3954) : warning C4244: 'argument' : conversion from 'b
    lpapi_Float64_t' to 'blpapi_Float32_t', possible loss of data
    blpapi/internals_wrap.cxx(4008) : warning C4244: 'argument' : conversion from 'b
    lpapi_Float64_t' to 'blpapi_Float32_t', possible loss of data
    blpapi/internals_wrap.cxx(4025) : warning C4244: 'argument' : conversion from 'b
    lpapi_Float64_t' to 'blpapi_Float32_t', possible loss of data
    c:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCR
    EMENTAL:NO /LIBPATH:C:\blp\API\APIv3\C++API\v3.7.5.1\lib /LIBPATH:C:\Anaconda\en
    vs\pyq\libs /LIBPATH:C:\Anaconda\envs\pyq\PCbuild blpapi3_32.lib /EXPORT:PyInit_
    _internals build\temp.win32-3.4\Release\blpapi/internals_wrap.obj /OUT:build\lib
    .win32-3.4\blpapi\_internals.pyd /IMPLIB:build\temp.win32-3.4\Release\blpapi\_in
    ternals.lib /MANIFESTFILE:build\temp.win32-3.4\Release\blpapi\_internals.pyd.man
    ifest /MANIFEST
       Creating library build\temp.win32-3.4\Release\blpapi\_internals.lib and objec
    t build\temp.win32-3.4\Release\blpapi\_internals.exp

    [pyq] H:\blpapi-py-master>python setup.py install
    running install
    running build
    running build_py
    running build_ext
    running install_lib
    copying build\lib.win32-3.4\blpapi\_internals.pyd -> C:\Anaconda\envs\pyq\Lib\si
    te-packages\blpapi
    running install_egg_info
    Removing C:\Anaconda\envs\pyq\Lib\site-packages\blpapi-3.5.5-py3.4.egg-info
    Writing C:\Anaconda\envs\pyq\Lib\site-packages\blpapi-3.5.5-py3.4.egg-info

But when I try to run it:

    [pyq] H:\blpapi-py-master\examples>python SimpleHistoryExample.py
    SimpleHistoryExample
    Connecting to localhost:8194
    Traceback (most recent call last):
      File "SimpleHistoryExample.py", line 86, in <module>
        main()
      File "SimpleHistoryExample.py", line 55, in main
        request.getElement("securities").appendValue("IBM US Equity")
      File "C:\Users\Bloomberg\AppData\Roaming\Python\Python34\site-packages\blpapi\
    element.py", line 675, in appendValue
        self.setValue(value, internals.ELEMENT_INDEX_END)
      File "C:\Users\Bloomberg\AppData\Roaming\Python\Python34\site-packages\blpapi\
    element.py", line 650, in setValue
        _ExceptionUtil.raiseOnError(traits[1](self.__handle, value, index))
    OverflowError: in method 'blpapi_Element_setValueString', argument 3 of type 'si
    ze_t'


For some reason my pyq environment is loading the library from `C:\Users\Bloomberg\AppData\Roaming\Python\Python34\site-packages\blpapi\` instead of `C:\Anaconda\envs\pyq\Lib\site-packages\blpapi`.

I copied the contents of the pyq environment into the Python AppData folder and it works as expected.  Is this like an anaconda environment thing?

**Comment by filmackay** [comment]
Yes looks like. If you are in the pyq virtualenv, you definitely want to be loading modules from there - I would certainly fix that first otherwise I don't think you know what would happen.
