### ISSUE TITLE
blpapi-py for python 3

### ISSUE THREAD

**Issue by zenith-matic** [filmackay/blpapi-py#4]
I just went through the instructions and managed to install it for python 2.7, which is nice, but what I want is to get it working on Python 3, like how do I go about it?   
    "python setup.py install"
works for Python 2. Is there like a trick to use it for Python 3 too?

**Comment by filmackay** [comment]
What platform are you on? I am using this library in python 3 on Ubuntu and Windows.

**Comment by zenith-matic** [comment]
I'm on Ubuntu 14.04. I also have a Windows partition but developing in there is a nightmare. Looking forward to your response

**Comment by filmackay** [comment]
Agree with you there - what error do you get when you run ths install command?

**Comment by zenith-matic** [comment]
I enter:

    python3 setup.py install

And get:

    Traceback (most recent call last):
    File "setup.py", line 44, in <module>
    raise Exception('Platform ' + Linux + ' is not supported')

What I did before running the above command, was go through all the changes highlighted here https://github.com/filmackay/blpapi-py/commit/ae6fa7f5344025e38d2546f1202d169fb141d870, hoping that it would be enough

**Comment by filmackay** [comment]
OK figured this out - python2 returns sys.platform == "linux2" whereas python3 is sys.platform == "linux". gah. Note this library is really for python 3.4 only, since SWIG is targeting that.

**Comment by filmackay** [comment]
@zenith-matic: did this resolve your problem?

**Comment by zenith-matic** [comment]
Sorry for the lateness, but it seems to have done the trick. Closing the issue
